<a href="https://colab.research.google.com/github/minsaee/ai_chat_python/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

## 1. 데이터 생성

In [10]:
# !pip install numpy

import numpy as np

np.zeros()

In [29]:
a = np.zeros(2)  # 1차원 배열 생성 = 벡터
a # array([0., 0.])
print(a)
print(dir(a))

[0. 0.]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__redu

In [30]:
print(a.__repr__)
print(a.__str__)
print(type(a))
print(a.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff9841181b0>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff9841181b0>
<class 'numpy.ndarray'>
(2,)


np.array()

In [31]:
a = np.array([1, 2]) # 벡터 생성
a # array([1, 2])
print(a)

[1 2]


In [19]:
# 2차원 배열 = 행렬

b = np.array([[1, 2],[3, 4]]) # 2행 2열
b # array([[1, 2],
  #       [3, 4]])
print(b)
print(dir(b))

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', 

In [21]:
print(a.__repr__)
print(a.__str__)
print(type(b))
print(b.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff999f6a310>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff999f6a310>
<class 'numpy.ndarray'>
(2, 2)


In [27]:
# 3차원 배열 이상 = 텐서(tensor)

c = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]]) # 2층(면, 공간), 2행, 2열
c # array([[[1, 2],
  #         [3, 4]],
  #       -  공 간  -
  #        [[5, 6],
  #         [7, 8]]])

print(c)
print(dir(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__ran

In [28]:
print(c.__repr__)
print(c.__str__)
print(type(c))
print(c.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff98424b270>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff98424b270>
<class 'numpy.ndarray'>
(2, 2, 2)


In [36]:
a = np.array([1, 2, 3])
print(a)
print(a[0]) # 특정 index 가져오기.
print(a[0:2]) # 슬라이싱 가져오기.

[1 2 3]
1
[1 2]


균질성 (Homogeneity)
 - 물리학에서 균질성은 어떤 물질 또는 시스템의 모든 지점에서 불규칙성이 없이 일정한 속성을 가지는 성질을 말한다.

In [37]:
# str 값이 하나라도 있으면 전체가 str로 변한다.
# array는 같은 type만 사용이 가능하다.
# 배열은 계산을 목적으로 하기에 일반적으로 str은 사용하지 않는다.
# numpy는 homogeneous

a = np.array([1, '2', 3])
print(a)
print(a[0])

['1' '2' '3']
1


In [42]:
a = np.array(['a', 1, True])
print(a)
print(a[1])

['a' '1' 'True']
1


In [43]:
# 논리값
# False = 0 , True = 1

a = np.array([0, False, 1, True])
print(a)
print(a[3])

[0 0 1 1]
1


np. zeros
 - tuple로 인자를 넣으면 그대로 모양을 만든다.
 - (2,3) : 2행 3열의 행렬을 만든다.
 - zeros는 기본값으로 0.으로 값을 모두 채운다.
  - np.zeros((2, 3))
  - np.zeros([2, 3])

In [50]:
a = np.zeros((2,3))
a # array([[0., 0., 0.],
  #       [0., 0., 0.]])

print(a)
print(a.shape)
print(type(a))

# np.zeros([2,3])의 결괏값도 동일하다.

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
<class 'numpy.ndarray'>


### np.eye
 - eye는 단위행렬
 - 숫자만 사용할 수 있다.

In [57]:
# eye는 행과 열의 크기를 지정할 수 있다.

a = np.eye(3)
a # array([[1., 0., 0.],
  #        [0., 1., 0.],
  #        [0., 0., 1.]])
print(a)
print(a.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [56]:
a = np.eye(3,2) # 3행 2열의 행렬 생성
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [63]:
# k에 index를 지정하면 1이 시작되는 위치를 지정할 수 있다.

a = np.eye(3,4, k=1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
 - 단위행렬(identity matrix)
 - 크기 한 개만 지정해서 생성할 수 있다.

In [66]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full
 - 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [72]:
# np.full(shape, fill_value)

a = np.full((3,3), 1) # 2행 2열의 행렬을 생성하고 1로 초기화 한다.
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [75]:
a = np.full((2,2), [1,2]) # 2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 한다.
a

array([[1, 2],
       [1, 2]])

In [76]:
a = np.full((2,2), [[1,2],[3,4]]) # 2행 2열의 행렬을 생성하고 각 셀마다 1, 2, 3, 4로 초기화 한다.
a

array([[1, 2],
       [3, 4]])

### np.empty
 - 배열을 생성하고 초기화를 지정하지 않는다.
 - 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [10]:
a = np.empty(3)
a # array([0. , 0.5, 1. ])

array([0. , 0.5, 1. ])

In [12]:
a = np.empty((2,3)) # 2행 3열의 배열 생성
a # array([[4.71016714e-310, 6.79542510e-310, 6.79542512e-310],
  #        [6.79542512e-310, 6.79544394e-310, 3.16202013e-322]])

array([[4.71016714e-310, 6.79542510e-310, 6.79542512e-310],
       [6.79542512e-310, 6.79544394e-310, 3.16202013e-322]])

### np.ones
 - 배열의 모든 값을 1로 채운다.

In [14]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

### _like
 - _like가 붙으면 shape가 같게 만들어진다.
 - 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.
 - eye_like는 제공하지 않는다.

In [16]:
a = np.array([[1,2,3],[4,5,6]]) # 2행 3열의 배열 생성
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b = np.ones_like(a) # a배열(2행 3열)의 shape을 복사 -> 생성
b

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
# array의 shape이 같아야 계산이 가능하다.

c = a + b
c

array([[2, 3, 4],
       [5, 6, 7]])

### linspace
 - 일정한 간격으로 값을 생성한다.
 - linspace(start,end, num, endpoint = True or False)
 ---
 - num은 생략 가능하다.
 - num을 생략하면 default value는 50이다.
 ---
 - endpoint가 True이면 포함, False면 탈락
 - endpoint는 생략 가능하다.
 - endpoint를 생략하면 True로 계산한다.

In [27]:
# 0부터 49까지 50개가 생성된다면,세 번째 num인자 값이 생략되어 있으므로
# start와 end 계산해서 default가 50이 생성된다.

a = np.linspace(0, 49) # linspace(0, 49) # num의 default value 50
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [35]:
a = np.linspace(0, 5)
a # 0부터 5사이에 있는 값을 50(default value)개 생성함.

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [30]:
a = np.linspace(0, 5, endpoint=False)
a # endpoint 탈락

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

### logspace
 - log scale을 사용한다.
 - logspace(start,end, num, endpoint = True or False)

In [37]:
# 1부터 50까지 사이의 10개의 요소를 생성.

a = np.logspace(1,50, 10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### arange
 - .arange(start, end, step)
 - start는 생략이 가능하다.
 - start를 생략하면 0부터 출력한다.
 - step은 생략이 가능하다.
 - step을 생략하면 1씩 증가한다.

## dtype (데이터 타입)

In [39]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [41]:
print(type(a))
print(a.dtype) # int64 : 정수 64bit(8byte)

<class 'numpy.ndarray'>
int64


In [44]:
# int8(1byte) -> -128 ~ 127
# 크기 범위를 넘어가면 쓰레기값을 나타냄.

b = np.array([1, 2, 3], dtype=np.int8)
b
print(b.dtype)

int8


In [62]:
b = np.array([-128, -127, 5, 100, 128], dtype=np.int8)
b


array([-128, -127,    5,  100, -128], dtype=int8)

In [64]:
# python의 datatype인 int를 지정하면 numpy의 int64와 같은 타입이다.

c = np.array([127, 2, 3, -128], dtype = int)
c

array([ 127,    2,    3, -128])

In [65]:
print(c.dtype)

int64


numpy 도움말

In [ ]:
np.lookfor('sum')

In [78]:
a = np.array([[1,2,3],[4,5,6]])

# 배열의 행렬을 알려준다.

a.shape

(2, 3)

In [79]:
# 배열이 몇차원인지 알려준다.

a.ndim

2

In [81]:
# 배열의 데이터타입을 알려준다.

a.dtype

dtype('int64')

In [82]:
# 배열의 요소의 개수를 알려준다.

a.size

6

In [83]:
# 요소당 byte수를 알려준다.
# 64bit = 8byte

a.itemsize

8

## numpy와 python의 속도차이

In [11]:
np.arange(10) # (start, end, step) start,step 생략 가능하다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# numpy를 이용한 계산

%time np.sum(np.arange(10000000))

CPU times: user 13.6 ms, sys: 24.2 ms, total: 37.7 ms
Wall time: 43.3 ms


49999995000000

In [5]:
# python을 이용한 계산

%time sum(range(100000000))

CPU times: user 2.2 s, sys: 10.6 ms, total: 2.21 s
Wall time: 2.25 s


4999999950000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [13]:
%time np.sum(np.arange(10000000))

CPU times: user 17.7 ms, sys: 24.2 ms, total: 41.9 ms
Wall time: 47.6 ms


49999995000000

In [14]:
%time np.sum(range(10000000))

CPU times: user 1.08 s, sys: 271 ms, total: 1.35 s
Wall time: 1.36 s


49999995000000

## copy
 - 대입문 6가지
  1. a = 1
  2. a = b = 1
  3. *b = 1, 2, 3 (tuple)
  4. a += 1
  5. global,nonlocal

python에서 copy

In [16]:
a = [1,2,3]

In [17]:
# shallow copy (얕은 카피)

b = a

In [18]:
b

[1, 2, 3]

In [19]:
# 메모리 주소 비교

a is b

True

In [20]:
# 서로 주소를 공유한다.
# b를 변경하면 a도 같이 변경된다.
b[0] = 7
print(b)
print(a)

[7, 2, 3]
[7, 2, 3]


In [27]:
# copy method를 사용하면 값은 같지만 주소는 공유하지 않는다.
# deep copy

a = [1, 2, 3]
b = a.copy()
a is b

False

In [29]:
# 값 비교

a == b

True

In [30]:
# b를 변경해도 a는 변경되지 않는다.

b[0] = 8

print(b)
print(a)

[8, 2, 3]
[1, 2, 3]


list가 2차원일때 copy

In [56]:
a = [[1,2,3],[4,5,6]]

In [42]:
type(a)

list

In [57]:
# shallow copy (얕은 카피)
b = a.copy()

In [58]:
# list가 2차원일 때는 copy method를 사용하면 1차원은 새로 생성하지만, 2차원은 공유한다.

print(a[0] is b[0]) # 주소 비교
print(a[0] == b[0]) # 값 비교

True
True


In [59]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [60]:
b[0][0] = 10

In [61]:
print(a[0])
print(a[0])

[10, 2, 3]
[10, 2, 3]


In [37]:
import copy

In [62]:
# deep copy (깊은 카피)

a = [[1,2,3],[4,5,6]]
b = copy.deepcopy(a)

In [65]:
print(a[0] is b[0]) # 주소 비교
print(a[0] == b[0]) # 값 비교

False
True


In [67]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [68]:
b[0][0] = 10

In [69]:
print(a[0])
print(b[0])

[1, 2, 3]
[10, 2, 3]


[ : ]는 전체를 의미한다.  
슬라이싱 방식으로 1차 리스트 일때는 재할당하면 deep copy가 된다.   
슬라이싱 방식으로 2차 리스트 이상일 경우는 shallow copy가 된다.

In [71]:
# deep copy

a = [1,2,3]
b = a[:]

print(a is b)

False


In [72]:
# shallow copy

a = [[1,2,3],[4,5,6]]
b = a[:]

print(a[0] is b[0])

True


In [74]:
a = [257, 2, 3]
b = a[:]

print(a == b)
print(a is b)

print(a[0] == b[0])
print(a[0] is b[0])

True
False
True
True


In [98]:
# intering
# python은 느리기 때문에 중간에 cache 저장하는 기법이 있다
# python에서는 -5에서 256까지는 같은 메모리 주소를 사용한다.
# 문자열에서 a-zA-Z0-9_는 내부적으로 intering 기법을 사용한다.

m = -6
n = -6
print(m is n)

k = 'python_가'
p = 'python_가'
print(k is p)

False
False
