<a href="https://colab.research.google.com/github/minsaee/ai_chat_python/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

## 1. 데이터 생성

In [252]:
# !pip install numpy

import numpy as np

np.zeros()

In [ ]:
a = np.zeros(2)  # 1차원 배열 생성 = 벡터
a # array([0., 0.])
print(a)
print(dir(a))

[0. 0.]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__redu

In [ ]:
print(a.__repr__)
print(a.__str__)
print(type(a))
print(a.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff9841181b0>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff9841181b0>
<class 'numpy.ndarray'>
(2,)


np.array()

In [ ]:
a = np.array([1, 2]) # 벡터 생성
a # array([1, 2])
print(a)

[1 2]


In [ ]:
# 2차원 배열 = 행렬

b = np.array([[1, 2],[3, 4]]) # 2행 2열
b # array([[1, 2],
  #       [3, 4]])
print(b)
print(dir(b))

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', 

In [ ]:
print(a.__repr__)
print(a.__str__)
print(type(b))
print(b.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff999f6a310>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff999f6a310>
<class 'numpy.ndarray'>
(2, 2)


In [ ]:
# 3차원 배열 이상 = 텐서(tensor)

c = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]]) # 2층(면, 공간), 2행, 2열
c # array([[[1, 2],
  #         [3, 4]],
  #       -  공 간  -
  #        [[5, 6],
  #         [7, 8]]])

print(c)
print(dir(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__ran

In [ ]:
print(c.__repr__)
print(c.__str__)
print(type(c))
print(c.shape)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7ff98424b270>
<method-wrapper '__str__' of numpy.ndarray object at 0x7ff98424b270>
<class 'numpy.ndarray'>
(2, 2, 2)


In [ ]:
a = np.array([1, 2, 3])
print(a)
print(a[0]) # 특정 index 가져오기.
print(a[0:2]) # 슬라이싱 가져오기.

[1 2 3]
1
[1 2]


균질성 (Homogeneity)
 - 물리학에서 균질성은 어떤 물질 또는 시스템의 모든 지점에서 불규칙성이 없이 일정한 속성을 가지는 성질을 말한다.

In [ ]:
# str 값이 하나라도 있으면 전체가 str로 변한다.
# array는 같은 type만 사용이 가능하다.
# 배열은 계산을 목적으로 하기에 일반적으로 str은 사용하지 않는다.
# numpy는 homogeneous

a = np.array([1, '2', 3])
print(a)
print(a[0])

['1' '2' '3']
1


In [ ]:
a = np.array(['a', 1, True])
print(a)
print(a[1])

['a' '1' 'True']
1


In [ ]:
# 논리값
# False = 0 , True = 1

a = np.array([0, False, 1, True])
print(a)
print(a[3])

[0 0 1 1]
1


np. zeros
 - tuple로 인자를 넣으면 그대로 모양을 만든다.
 - (2,3) : 2행 3열의 행렬을 만든다.
 - zeros는 기본값으로 0.으로 값을 모두 채운다.
  - np.zeros((2, 3))
  - np.zeros([2, 3])

In [ ]:
a = np.zeros((2,3))
a # array([[0., 0., 0.],
  #       [0., 0., 0.]])

print(a)
print(a.shape)
print(type(a))

# np.zeros([2,3])의 결괏값도 동일하다.

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
<class 'numpy.ndarray'>


### np.eye
 - eye는 단위행렬
 - 숫자만 사용할 수 있다.

In [ ]:
# eye는 행과 열의 크기를 지정할 수 있다.

a = np.eye(3)
a # array([[1., 0., 0.],
  #        [0., 1., 0.],
  #        [0., 0., 1.]])
print(a)
print(a.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [ ]:
a = np.eye(3,2) # 3행 2열의 행렬 생성
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# k에 index를 지정하면 1이 시작되는 위치를 지정할 수 있다.

a = np.eye(3,4, k=1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
 - 단위행렬(identity matrix)
 - 크기 한 개만 지정해서 생성할 수 있다.

In [ ]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full
 - 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [ ]:
# np.full(shape, fill_value)

a = np.full((3,3), 1) # 2행 2열의 행렬을 생성하고 1로 초기화 한다.
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full((2,2), [1,2]) # 2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 한다.
a

array([[1, 2],
       [1, 2]])

In [ ]:
a = np.full((2,2), [[1,2],[3,4]]) # 2행 2열의 행렬을 생성하고 각 셀마다 1, 2, 3, 4로 초기화 한다.
a

array([[1, 2],
       [3, 4]])

### np.empty
 - 배열을 생성하고 초기화를 지정하지 않는다.
 - 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [ ]:
a = np.empty(3)
a # array([0. , 0.5, 1. ])

array([0. , 0.5, 1. ])

In [ ]:
a = np.empty((2,3)) # 2행 3열의 배열 생성
a # array([[4.71016714e-310, 6.79542510e-310, 6.79542512e-310],
  #        [6.79542512e-310, 6.79544394e-310, 3.16202013e-322]])

array([[4.71016714e-310, 6.79542510e-310, 6.79542512e-310],
       [6.79542512e-310, 6.79544394e-310, 3.16202013e-322]])

### np.ones
 - 배열의 모든 값을 1로 채운다.

In [ ]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

### _like
 - _like가 붙으면 shape가 같게 만들어진다.
 - 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.
 - eye_like는 제공하지 않는다.

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) # 2행 3열의 배열 생성
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.ones_like(a) # a배열(2행 3열)의 shape을 복사 -> 생성
b

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# array의 shape이 같아야 계산이 가능하다.

c = a + b
c

array([[2, 3, 4],
       [5, 6, 7]])

### linspace
 - 일정한 간격으로 값을 생성한다.
 - linspace(start,end, num, endpoint = True or False)
 ---
 - num은 생략 가능하다.
 - num을 생략하면 default value는 50이다.
 ---
 - endpoint가 True이면 포함, False면 탈락
 - endpoint는 생략 가능하다.
 - endpoint를 생략하면 True로 계산한다.

In [ ]:
# 0부터 49까지 50개가 생성된다면,세 번째 num인자 값이 생략되어 있으므로
# start와 end 계산해서 default가 50이 생성된다.

a = np.linspace(0, 49) # linspace(0, 49) # num의 default value 50
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [ ]:
a = np.linspace(0, 5)
a # 0부터 5사이에 있는 값을 50(default value)개 생성함.

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
a = np.linspace(0, 5, endpoint=False)
a # endpoint 탈락

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

### logspace
 - log scale을 사용한다.
 - logspace(start,end, num, endpoint = True or False)

In [ ]:
# 1부터 50까지 사이의 10개의 요소를 생성.

a = np.logspace(1,50, 10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### arange
 - .arange(start, end, step)
 - start는 생략이 가능하다.
 - start를 생략하면 0부터 출력한다.
 - step은 생략이 가능하다.
 - step을 생략하면 1씩 증가한다.

## dtype (데이터 타입)

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(a.dtype) # int64 : 정수 64bit(8byte)

<class 'numpy.ndarray'>
int64


In [ ]:
# int8(1byte) -> -128 ~ 127
# 크기 범위를 넘어가면 쓰레기값을 나타냄.

b = np.array([1, 2, 3], dtype=np.int8)
b
print(b.dtype)

int8


In [ ]:
b = np.array([-128, -127, 5, 100, 128], dtype=np.int8)
b


array([-128, -127,    5,  100, -128], dtype=int8)

In [ ]:
# python의 datatype인 int를 지정하면 numpy의 int64와 같은 타입이다.

c = np.array([127, 2, 3, -128], dtype = int)
c

array([ 127,    2,    3, -128])

In [ ]:
print(c.dtype)

int64


numpy 도움말

In [ ]:
np.lookfor('sum')

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

# 배열의 행렬을 알려준다.

a.shape

(2, 3)

In [ ]:
# 배열이 몇차원인지 알려준다.

a.ndim

2

In [ ]:
# 배열의 데이터타입을 알려준다.

a.dtype

dtype('int64')

In [ ]:
# 배열의 요소의 개수를 알려준다.

a.size

6

In [ ]:
# 요소당 byte수를 알려준다.
# 64bit = 8byte

a.itemsize

8

## numpy와 python의 속도차이

In [ ]:
np.arange(10) # (start, end, step) start,step 생략 가능하다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# numpy를 이용한 계산

%time np.sum(np.arange(10000000))

CPU times: user 13.6 ms, sys: 24.2 ms, total: 37.7 ms
Wall time: 43.3 ms


49999995000000

In [ ]:
# python을 이용한 계산

%time sum(range(100000000))

CPU times: user 2.2 s, sys: 10.6 ms, total: 2.21 s
Wall time: 2.25 s


4999999950000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [ ]:
%time np.sum(np.arange(10000000))

CPU times: user 17.7 ms, sys: 24.2 ms, total: 41.9 ms
Wall time: 47.6 ms


49999995000000

In [ ]:
%time np.sum(range(10000000))

CPU times: user 1.08 s, sys: 271 ms, total: 1.35 s
Wall time: 1.36 s


49999995000000

## copy
 - 대입문 6가지
  1. a = 1
  2. a = b = 1
  3. *b = 1, 2, 3 (tuple)
  4. a += 1
  5. global,nonlocal

python에서 copy

In [ ]:
a = [1,2,3]

In [ ]:
# shallow copy (얕은 카피)

b = a

In [ ]:
b

[1, 2, 3]

In [ ]:
# 메모리 주소 비교

a is b

True

In [ ]:
# 서로 주소를 공유한다.
# b를 변경하면 a도 같이 변경된다.
b[0] = 7
print(b)
print(a)

[7, 2, 3]
[7, 2, 3]


In [ ]:
# copy method를 사용하면 값은 같지만 주소는 공유하지 않는다.
# deep copy

a = [1, 2, 3]
b = a.copy()
a is b

False

In [ ]:
# 값 비교

a == b

True

In [ ]:
# b를 변경해도 a는 변경되지 않는다.

b[0] = 8

print(b)
print(a)

[8, 2, 3]
[1, 2, 3]


list가 2차원일때 copy

In [8]:
a = [[1,2,3],[4,5,6]]

In [ ]:
type(a)

list

In [9]:
# shallow copy (얕은 카피)
b = a.copy()

In [10]:
# list가 2차원일 때는 copy method를 사용하면 1차원은 새로 생성하지만, 2차원은 공유한다.

print(a[0] is b[0]) # 주소 비교
print(a[0] == b[0]) # 값 비교

True
True


In [ ]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [ ]:
b[0][0] = 10

In [ ]:
print(a[0])
print(a[0])

[10, 2, 3]
[10, 2, 3]


In [253]:
import copy

In [ ]:
# deep copy (깊은 카피)

a = [[1,2,3],[4,5,6]]
b = copy.deepcopy(a)

In [ ]:
print(a[0] is b[0]) # 주소 비교
print(a[0] == b[0]) # 값 비교

False
True


In [ ]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [ ]:
b[0][0] = 10

In [ ]:
print(a[0])
print(b[0])

[1, 2, 3]
[10, 2, 3]


[ : ]는 전체를 의미한다.  
슬라이싱 방식으로 1차 리스트 일때는 재할당하면 deep copy가 된다.   
슬라이싱 방식으로 2차 리스트 이상일 경우는 shallow copy가 된다.

In [ ]:
# deep copy

a = [1,2,3]
b = a[:]

print(a is b)

False


In [ ]:
# shallow copy

a = [[1,2,3],[4,5,6]]
b = a[:]

print(a[0] is b[0])

True


In [ ]:
a = [257, 2, 3]
b = a[:]

print(a == b)
print(a is b)

print(a[0] == b[0])
print(a[0] is b[0])

True
False
True
True


In [ ]:
# intering
# python은 느리기 때문에 중간에 cache 저장하는 기법이 있다
# python에서는 -5에서 256까지는 같은 메모리 주소를 사용한다.
# 문자열에서 a-zA-Z0-9_는 내부적으로 intering 기법을 사용한다.

m = -6
n = -6
print(m is n)

k = 'python_가'
p = 'python_가'
print(k is p)

False
False


In [ ]:
z = -6
x = z
v = -6

print(id(z))
print(id(x))
print(id(v))

137956654318480
137956654318480
137956654324336


In [28]:
a = [[1,2,3],[4,5,6]]
b = a.copy()
print(a)
print(b)
print(id(a))
print(id(b))
print(a is b)
print('-----------')
print(a[0])
print(b[0])
print(id(a[0]))
print(id(b[0]))
print(a[0] is b[0])
print('-----------')
print(a[0][0])
print(b[0][0])
print(id(a[0][0]))
print(id(b[0][0]))
print(a[0][0] is b[0][0])
print('-----------')


[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]
138287270974848
138287270972928
False
-----------
[1, 2, 3]
[1, 2, 3]
138287270982336
138287270982336
True
-----------
1
1
138288543498480
138288543498480
True
-----------


In [27]:
a = [[1,2,3],[4,5,6]]
c = copy.deepcopy(a)
print(a)
print(c)
print(id(a))
print(id(c))
print(a is c)
print('-----------')
print(a[0])
print(c[0])
print(id(a[0]))
print(id(c[0]))
print(a[0] is c[0])
print('-----------')
print(a[0][0])
print(c[0][0])
print(id(a[0][0]))
print(id(c[0][0]))
print(a[0][0] is c[0][0])
print('-----------')


[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]
138287271375808
138287271378816
False
-----------
[1, 2, 3]
[1, 2, 3]
138287271494208
138287271494400
False
-----------
1
1
138288543498480
138288543498480
True
-----------


In [29]:
# numpy에서는 값을 각자 비교해서 bool값을 준다.

a = b = np.array([1,2,3])

In [30]:
print(a is b)
print(a == b)

True
[ True  True  True]


In [32]:
# numpy는 indexing이 가능하다.

a[0]

1

In [34]:
# numpy는 slicing이 가능하다.

a[:]

array([1, 2, 3])

In [38]:
a[0] = 100
print(a[0])
print(b[0])

100
100


array는 homogeneous, sequence, mutable 이다.   
list는 heterogeneous, sequence, mutable 이다.

In [48]:
# numpy의 copy method는 deep copy이다.

a = np.array([[1,2,3],[4,5,6]])
b = a.copy()

print(a)
print(b)
print(id(a))
print(id(b))
print(a is b)
print(a == b)
print('-----------')
print(a[0])
print(b[0])
print(id(a[0]))
print(id(b[0]))
print(a[0] is b[0])
print(a[0] == b[0])
print('-----------')
print(a[0][0])
print(b[0][0])
print(id(a[0][0]))
print(id(b[0][0]))
print(a[0][0] is b[0][0])
print(a[0][0] == b[0][0])
print('-----------')

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
138287269654000
138287269653424
False
[[ True  True  True]
 [ True  True  True]]
-----------
[1 2 3]
[1 2 3]
138287269655632
138287269655632
False
[ True  True  True]
-----------
1
1
138287272299536
138287272309936
False
True
-----------


### as 계열
 - 다른 데이터 타입을 가져와 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [51]:
# list를 array로 바꾸기.

a = [1.5, 2.5, 3.5]
b = np.array(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [52]:
# list를 as를 이용해 array로 바꾸기.

a = [1.5, 2.5, 3.5]
b = np.asarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [55]:
# list를 asf를 이용해 int값을 float64값으로 하는 array로 바꾸기.

a = [15, 25, 35] # int
b = np.asfarray(a) # float64

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'int'>
<class 'numpy.float64'>


In [57]:
a = [1.5, 2.5, 3.5]
b = np.asarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


### 값 가져오기

---

(1) indexing, slicing 방법   
(2) boolean indexing 방법  
(3) fancy indexing 방법

In [59]:
a = [[1,2,3],[4,5,6]] # python의 list
b = np.array([[1,2,3],[4,5,6]]) # numpy의 array

In [72]:
print(a[0])
print(b[0])
print(type(a[0]))
print(type(b[0]))

# print(a[0,1]) # TypeError: list indices must be integers or slices, not tuple
print(b[0,1]) # 0번째 행 1번째 열
print(b[0][1]) # 0번째 행 1번째 열


[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
2
2


In [78]:
print(a[slice(0,1)]) # 0행부터 1행 미만의 데이터를 가져온다. 원래의 차원값이 유지된다.
print(a[0]) # 원래의 차원값이 유지가 안되고, 1차원으로 가져온다.

[[1, 2, 3]]
[1, 2, 3]


numpy는 기본적으로 indexing/slicing할 때 comma를 사용할 수 있다.
 - indexing
  - [행,열]  
  - [행][열]

 - slicing
  - [행:행 열:열]

In [82]:
# indexing
print(b[0,1])
print(b[0][1])
print(b[0, -1])

# slicing 원래의 차원값이 유지된다.
print(b[0:1,0:2])
print(b[0:2,0:2])

2
2
3
[[1 2]]
[[1 2]
 [4 5]]


In [116]:
# python의 indexing
print(a[0][1])

# python의 slicing
print(a[0:1])
print(a[0:1][0:1])

print(id(a[0]))
print(id(a[0:1]))
print(id(a[0:1][0:1]))

2
[[1, 2, 3]]
[[1, 2, 3]]
138287271603712
138287269211264
138287269211072


boolean indexing
 - array만 가능하다.
 - numpy True, False로만 가능하다.
 - shape이 맞아야 가능하다.
 - array는 scalar와 연산하면 elementwise로 계산한다.  
 (element wise : 원소별로 각각 계산한다.)

In [117]:
a = [[1,2,3],[4,5,6]]

In [120]:
# a>3 # TypeError: '>' not supported between instances of 'list' and 'int'

In [147]:
b = np.array([[1,2,3,4]])
c = np.array([[2,2,2,2]])
b > c # array([[False, False,  True,  True]])

# scalar와 연산하기
b > 2 # array([[False, False,  True,  True]])

array([[False, False,  True,  True]])

In [143]:
# True값만 가져오기

b[np.array([[False,False,True,True]])]

array([3, 4])

In [144]:
b[b>2]

array([3, 4])

In [155]:
# python에서는 boolean indexing을 지원 안한다.

a = [[1,2,3,4]]
# a[[False,False,True,True]] # TypeError: list indices must be integers or slices, not list

(3) fancy indexing

 - [[행],[열]]
 - 행과 열의 개수를 같게 지정해야 한다.  
 - silcing은 fancy에서 사용할 수 없다.  

In [181]:
# 0 ~ 99 까지 1차원으로 출력
# np.arange(start, end, step) -> start와 step은 생략가능하다.

a = np.arange(100)
print(a)

# 배열의 구조 변경
# reshape(행 개수, 열 개수)
b = a.reshape(20, 5) # reshape는 개수가 맞아야한다.
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [190]:
print(b[1,3]) # 1행 3열의 값
print(b[1][3]) # 1행 3열의 값
print(b[1:3, 2:4]) # 1행부터 3행미만, 2열부터 4열 미만의 데이터
print(b[[1,3,5],[0,2,4]]) # 1행 0열, 3행 2열, 5행 4열의 데이터
print(b[[1,3,5]]) # 1, 3, 5행의 데이터

# [silcing,[fancy]]로는 사용할 수 있다.
print(b[:,[0,2,4]]) # 모든 행의 0,2,4의 데이터

print(b[[1,3,4],[0]]) # broadcast -> 1, 3, 4행의 0열의 데이터

8
8
[[ 7  8]
 [12 13]]
[ 5 17 29]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]
[ 5 15 20]


In [199]:
m = np.array([[1,2],[3,4]])
n = np.array([[2,2]])
print(m)
print(n)


[[1 2]
 [3 4]]
[[2 2]]


In [200]:
# broadcast

m+n # [1,2]+[2,2], [3,4]+[2,2]가 계산된다.

array([[3, 4],
       [5, 6]])

In [232]:
m = np.arange(12).reshape(2,6)
print(m)
n = np.array([[1,2,3,4,5,6]])
print(n)
print(m + n)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1 2 3 4 5 6]]
[[ 1  3  5  7  9 11]
 [ 7  9 11 13 15 17]]


### 3차원이상에서 차원 구분법

In [262]:
# 3차원 구조 만들기
# 기본적으로 대괄호의 개수로 구분하면 된다.

b = np.arange(24).reshape(2,3,4) # 2면(2층, 2공간), 3행, 4열
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [242]:
# indexing으로 2차원으로 반환하기.

b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [243]:
# indxing으로 1차원으로 반환하기.

b[0][0]

array([0, 1, 2, 3])

In [244]:
b[1,1] # 1공간, 1행, 모든열

array([16, 17, 18, 19])

In [246]:
b[0,1,3] # 0공간, 1행, 3열

7

In [247]:
b[:, 1, 3] # 모든공간, 1행 ,3열

array([ 7, 19])

In [263]:
b[:, :, 1] # 모든공간, 모든행 ,1열

array([[ 1,  5,  9],
       [13, 17, 21]])

In [260]:
# braoadcast 이용해서 (4,4)만들기

a = np.array([[0],[10],[20],[30]])
print(a.shape)
b = np.array([[1,2,3,4]])
print(b.shape)
a+b

(4, 1)
(1, 4)


array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

### fancy indexing과 indexing의 차이
 - indexing은 원래 차원에서 하나 감소해서 가져오고,  
   fancy indexing은 원래 차원으로 가져온다.

In [264]:
# indexing은 차원이 하나 감소해서 가져온다.
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [280]:
# fancy indexing은 차원이 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## Ellipsis
...(Ellipsis)는 이후로 모든 것을 의미한다.

In [285]:
# b[0] = b[0,:,:] = b[0,...]

b[0] # indexing의 생략 기법
b[0,:,:] # slicing
b[0,...] # ellipsis

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [289]:
# 숫자 1,5,9 가져오기

b[0, : ,1]

array([1, 5, 9])

In [293]:
b[[0], :, [1]]

array([[1, 5, 9]])

In [295]:
# 숫자 1,5,9,3,7,11 가져오기
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [309]:
# 숫자 4,5,6,7,16,17,18,19 가져오기
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [310]:
b[:,1:2,:]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [312]:
b[[0,1],[1]]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [306]:
b[[0,1],1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [303]:
b[:,[1]]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [313]:
# 숫자 3,7,11,15,19,23 가져오기
b[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [315]:
b[:,:,3:4]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [317]:
b[:,:,[-1]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [324]:
b[...,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

## 줄임표현(...)
출력해야할 데이터 수가 클 때 보이는 ...은 ellipsis와 다르다

In [326]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [328]:
# ... 양쪽의 출력값 개수 지정 (default 3개)

np.set_printoptions(edgeitems=6)

In [329]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999])

## 연산
 - numpy연산의 기본은 두 개의 shape가 같아야한다.

In [330]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [335]:
a.shape
b = np.arange(1,13).reshape(3,4)

In [337]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

numpy는 elementwise로 vectorize 연산을 한다.  
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [338]:
# shape이 같으면 elementwise가 가능하다

a+b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
# python의 list에서 + 연산자는 list를 확장시킨다. (연결)
[1,2,3] + [4,5,6]

In [341]:
# list로 vectorize 하기

@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3],[4,5,6])

array([5, 7, 9])

In [351]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [352]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [345]:
# array에서는 각 위치의 원소끼리 곱하기가 가능하다.

a*b # elementwise

array([[ 0,  7, 16],
       [27, 40, 55]])

In [347]:
# python에서 list끼리 *(곱하기)는 불가능하다.

a = [1,2,3]
b = [4,5,6]

# a*b # TypeError: can't multiply sequence by non-int of type 'list'

In [348]:
# 매트릭스 함수를 이용한 행렬 생성
# matirx에서는 행렬곱으로 *와 @를 모두 사용 가능하다.

c = np.matrix([[1,2],[3,4]])
c # <class 'numpy.matrix'>

matrix([[1, 2],
        [3, 4]])

In [391]:
c*c

matrix([[ 7, 10],
        [15, 22]])

In [392]:
c@c

matrix([[ 7, 10],
        [15, 22]])

ndarray에서 행렬곱 연산자는 @이다.     
2행 3열 @ 3행 2열 -> 계산 (3열,3행) 결과 (2행, 2열)  
계산하는 행과 열의 shape이 맞아야한다.  
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [361]:
a= np.arange(6).reshape(2,3)
b= np.arange(1,7).reshape(3,2)

a@b

array([[13, 16],
       [40, 52]])

행렬곱을 하기 위해서는 shape가 맞아야한다.  
T는 transpose(전치)의 약자이다.

In [381]:
print(a)
print(a.shape)
print('\n')
print(a.T)
print(a.T.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [378]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

In [427]:
a = np.arange(1,17).reshape(1,16)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [405]:
a.T

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [394]:
a @ a.T

array([[1496]])

함수방법으로 np.dot()함수를 사용할 수 있다.

In [396]:
# function 방식

np.dot(a, a.T)

array([[1496]])

In [397]:
np.dot(c, c)

matrix([[ 7, 10],
        [15, 22]])

In [406]:
# method 방식

a.dot(a.T)

array([[1496]])

## strides
strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.  
c의 포인터 개념을 알고 있으면 이해가 쉽다.

In [407]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [408]:
# 행의 메모리 간격은 32bytes
# 열의 메모리 간격은 8bytes

a.strides

(32, 8)

In [409]:
a.dtype

dtype('int64')

In [410]:
# 열의 원소 갯수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격

a.itemsize

8

### axis
 aixs는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [431]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [432]:
# numpy에서도 sum이 제공이 된다.

np.sum(a)

66

In [438]:
# a배열은 2차원이므로 axis = 0은 행기준

np.sum(a, axis=0)

array([12, 15, 18, 21])

In [440]:
# a배열은 2차원이므로 axis = 1은 열기준


np.sum(a, axis=1)

array([ 6, 22, 38])

In [436]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [445]:
# b배열은 3차원이므로 axis = 0은 층기준

np.sum(b, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [447]:
# 3차원 array이기에 행기준일시 array가 2개 리턴된다.

np.sum(b, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [449]:
# 3차원 array이기에 열기준일시 array가 2개 리턴된다.

np.sum(b, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [451]:
c = np.arange(16).reshape(2,2,2,2)
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [452]:
np.sum(c, axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [454]:
np.sum(c, axis=1)

array([[[ 4,  6],
        [ 8, 10]],

       [[20, 22],
        [24, 26]]])

In [456]:
np.sum(c, axis=2)

array([[[ 2,  4],
        [10, 12]],

       [[18, 20],
        [26, 28]]])

In [457]:
np.sum(c, axis=3)

array([[[ 1,  5],
        [ 9, 13]],

       [[17, 21],
        [25, 29]]])

In [459]:
c = np.arange(32).reshape(2,2,2,2,2)
c

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [473]:
np.sum(c, axis=1)

array([[[[ 8, 10],
         [12, 14]],

        [[16, 18],
         [20, 22]]],


       [[[40, 42],
         [44, 46]],

        [[48, 50],
         [52, 54]]]])

## array 모양 바꾸기
(1) reshape
 - reshape은 차원을 바꿔주는 기능을 한다.
 - 음수를 쓰면, 알아서 shape을 맞춘다.
 - 음수값은 아무거나 상관없다.

In [469]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])