<a href="https://colab.research.google.com/github/minsaee/ai_chat_python/blob/master/400_pandas_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Version

In [8]:
# python version
import sys
print(sys.version)

!python --version

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Python 3.10.12


In [7]:
# numpy version
import numpy as np
print(np.__version__)

1.23.5


In [6]:
# pandas version
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
!pip freeze

In [2]:
# 구글 드라이브 연동

from google.colab import drive
drive.mount('/content/drive')

%cd '/content/drive/MyDrive/ai_chat_python'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/ai_chat_python


## 파일 형식 데이터 불러오기

In [ ]:
print(type(pd))
print(dir(pd))

<class 'module'>
['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'annotations', 'api', 'arra

In [ ]:
# header 키워드를 지정하지 않고 호출하면 파일의 첫줄을 header로 호출된다.
# 첫번째 줄을 column으로 처리한다.
# header파라미터의 default:'infer'

data = pd.read_csv('./source/num.txt')
print(data)
print(type(data)) # <class 'pandas.core.frame.DataFrame'>
print(dir(data))

   1  2  3  4   5
0  6  7  8  9  10
<class 'pandas.core.frame.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__redu

In [ ]:
data = pd.read_csv('./source/num.txt', header=None) # header 지정하기.
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
# 열을 기준으로 가져오기.
# 열의 요소는 Series
# 열이 2개 이상이면 frame

print(data[0]) # data.[컬럼명(열)]
print(type(data[0])) # <class 'pandas.core.series.Series'>
print(dir(data[0]))

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__r

In [ ]:
# 행을 기준으로 가져오기.

print(data.iloc[0]) # data.iloc[index(행)]
print(type(data.iloc[0])) # <class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


### numpy와 list 비교

In [ ]:
# numpy
a = np.arange(12).reshape(3,4)
print(type(a))
print(a)

print(a[1][2]) # a[행][열]
print(a[1,2]) # a[행,열]

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
6


In [ ]:
# list
b = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
print(type(b))
print(b)
print(b[1][2]) # list에서 slicing,boolean,indexing,fancy indexing 안됨

<class 'list'>
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
6


In [ ]:
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
# .values()하면 numpy 포맷으로 변환된다.
# 내부적으로 numpy로 되어있어서 가능하다.

print(data.values)
print(type(data.values)) # <class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
# __array__가 있으면 numpy와 호환이 가능하다.
print(dir(data))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul_

### 웹 주소에서 데이터 불러오기

In [9]:
# header는 기본이 첫줄을 column으로 가져오게 설정되어 있기에 header='infer' 생략이 가능하다.

data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
# default 앞의 5개를 출력한다.
# 개수 지정이 가능하다.

data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [ ]:
# default 끝의 5개를 출력한다.
# 개수 지정이 가능하다.

data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# default Random 1개를 출력한다.
# 개수 지정이 가능하다.

data.sample()

total_bill  tip     sex smoker  day    time  size
52       34.81  5.2  Female     No  Sun  Dinner     4

In [ ]:
data.sample(5)

total_bill   tip     sex smoker  day    time  size
20        17.92  4.08    Male     No  Sat  Dinner     2
168       10.59  1.61  Female    Yes  Sat  Dinner     2
21        20.29  2.75  Female     No  Sat  Dinner     2
171       15.81  3.16    Male    Yes  Sat  Dinner     2
165       24.52  3.48    Male     No  Sun  Dinner     3

In [ ]:
# array만 가져오기.
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
# index만 가져오기.
data.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
# column만 가져오기
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# dict 타입
dicdata = {'name':'홍길동','age':'30'}

print(dicdata['name'])
# print(dicdata.name)  # AttributeError: 'dict' object has no attribute 'name'

홍길동


In [ ]:
print(dir(dict))
print(dicdata.items())

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
dict_items([('name', '홍길동'), ('age', '30')])


### pandas는 dictionary와 attribute 방식을 모두 사용할 수 있다.

In [ ]:
# dictionary 방식 이용
print(data['tip'])

# attribute 방식 이용
print(data.tip)

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [ ]:
# column은 fancy indexing을 이용할 수 있다.
# data[열]이므로 행을 이용해서는 가져올 수 없다. # KeyError

print(data[['smoker','day']])



print(data.iloc[[0,3,6]])
print(data.iloc[0:3])

    smoker   day
0       No   Sun
1       No   Sun
2       No   Sun
3       No   Sun
4       No   Sun
..     ...   ...
239     No   Sat
240    Yes   Sat
241    Yes   Sat
242     No   Sat
243     No  Thur

[244 rows x 2 columns]
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
6        8.77  2.00    Male     No  Sun  Dinner     2
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3


In [ ]:
# column은 slicing을 이용할 수 없다.
# data['tip':'day'] # TypeError: cannot do slice indexing on RangeIndex with these indexers [tip] of type str


# rows는 slicing을 이용할 수 있다.
print(data[0:3])

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3


In [ ]:
print(type(data.iloc[3]))
print(data.iloc[3])
print(data['tip'])

<class 'pandas.core.series.Series'>
total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


하나의 column 또는 행을 가져오면 Series로 리턴한다.  
fancy indexing을 이용해서 하나의 column 또는 행을 가져오면
DataFrame으로 리턴한다.

In [ ]:
data[['tip','smoker']] # DataFrame
data.iloc[1:3] # DataFrame
data.iloc[1:3, :]

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [ ]:
data.iloc[0:5, 1:3] # data.iloc[행index, 열index]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female

In [ ]:
# fancy indexing
data.iloc[[0,3,5],[1,3,4]]

tip smoker  day
0  1.01     No  Sun
3  3.31     No  Sun
5  4.71     No  Sun

In [ ]:
print(data)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [ ]:
data.iloc[3][1] # 3행 1열
data.iloc[3,1] # 3행 1열

3.31

In [ ]:
data.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

iloc는 번호를 이용해서 가져오고, loc는 이름을 이용해서 가져온다.

In [ ]:
data.loc[0,'tip'] # data.loc[행이름(rows), 열이름(column)]

1.01

In [ ]:
data.iloc[0,1] # data.loc[행번호(index), 열번호(index)]

1.01

In [ ]:
data['tip'][0] # data[열이름][행이름]

1.01

In [ ]:
data.loc[0:3,'tip':'smoker'] # data.loc[행이름:행이름, 열이름:열이름]

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No
3  3.31    Male     No

In [ ]:
data.iloc[0:4,0:4]

total_bill   tip     sex smoker
0       16.99  1.01  Female     No
1       10.34  1.66    Male     No
2       21.01  3.50    Male     No
3       23.68  3.31    Male     No

In [ ]:
data.loc[[0,3,5],['tip','day','time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

In [ ]:
data.iloc[[0,3,5],[1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

## at
 - 이름으로 한 위치의 값만 가져온다.
 - at은 slicing을 사용할 수 없다.
 - at은 fancy indexing을 사용할 수 없다.

In [ ]:
# print(data['tip',0]) # KeyError: ('tip', 0)
print(data.at[0,'tip'])
print(data.loc[0,'tip'])
print(data.iloc[0,1])


print(data['tip'][0])
# print(data.at[0]['tip']) # TypeError: DataFrame._get_value() missing 1 required positional argument: 'col'
print(data.loc[0]['tip'])
print(data.iloc[0][1])

print(data['tip']) # 열(이름)
print(data[3:5]) # 행(번호)

1.01
1.01
1.01
1.01
1.01
1.01
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
   total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


In [ ]:
# column

print(data[['tip','day']])
# data['tip':'day'] # TypeError

# rows
print(data[0:5])
# data[[0,1]] # KeyError

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


### iat
 - iat은 번호로 한 위치의 값을 가져온다.
 - iat은 slicing을 사용할 수 없다.
 - iat은 fancy indexing을 사용할 수 없다.

In [ ]:
print(data.iat[0,1])
print(data.at[0,'tip'])

1.01
1.01


### boolean indexing

In [ ]:
data.tip >= 5
data['tip'] >= 5

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [ ]:
data[data['tip'] >= 5]

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
data[data['tip'] >= 5]['tip']

11      5.00
23      7.58
39      5.00
44      5.60
46      5.00
47      6.00
52      5.20
59      6.73
73      5.00
83      5.00
85      5.17
88      5.85
116     5.07
141     6.70
142     5.00
143     5.00
155     5.14
156     5.00
170    10.00
172     5.15
181     5.65
183     6.50
185     5.00
197     5.00
211     5.16
212     9.00
214     6.50
239     5.92
Name: tip, dtype: float64

In [ ]:
data[data['tip'] >= 5].loc[:, 'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip'] >= 5].iloc[:, 1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data['tip'][0]

1.01

요일이 'Sun'이거나 'Sat'의 'tip'과 'day'의 값을 가져오기

In [ ]:
# 요일이 'Sun'이거나'Sat'
# or -> | 사용
rs = data[(data['day']=='Sun') | (data['day']=='Sat')]

rs['day'].unique()

# fancy indexing으로 'tip'과'day'의 값 가져오기
rs[['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [ ]:
data[(data['day']=='Sun') | (data['day']=='Sat')][['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [10]:
print(data.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


In [11]:
data.shape

(244, 7)

In [13]:
data.size

1708

In [21]:
# columns 이름을 바꿀때 mapper 이용하기.

data2 = data.rename(mapper={'size':'size_'}, axis=1)
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

In [23]:
# columns 이름을 바꿀때 columns 이용하기.

data2 = data.rename(columns={'size':'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

### category
 - category는 문자열(object)보다 더 많은 기능을 할 수 있다.
 - category는 문자 또는 숫자도 가능하다.
 - category는 몇 개로 분류할 수 있을 때 발생한다. ex)성별(남,여)

In [25]:
print(data['sex'].dtype)

object


In [27]:
data['sex']= data['sex'].astype('category') # type : object -> catagory

In [28]:
print(data['sex'].dtype)

category


In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    object  
 4   day         244 non-null    object  
 5   time        244 non-null    object  
 6   size        244 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(3)
memory usage: 11.9+ KB


In [31]:
data[data['sex']=='Female']['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

금요일에 온 여자만 가져오기

In [46]:
data['day']=='Fri'

data[data['day']=='Fri']['day'].unique()
data[data['sex']=='Female']['sex'].unique()

data[(data['sex']=='Female') & (data['day']=='Fri')]['day'].unique
data[(data['sex']=='Female') & (data['day']=='Fri')]['sex'].unique

<bound method Series.unique of 92     Female
93     Female
94     Female
100    Female
101    Female
221    Female
223    Female
225    Female
226    Female
Name: sex, dtype: category
Categories (2, object): ['Female', 'Male']>

In [40]:
data[(data['sex']=='Female') & (data['day']=='Fri')]

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

### describe
 - describe는 기초적인 통게분석을 해주는 함수이다.

In [47]:
# 기본적으로 숫자로 되어 있는 columns만 가져온다.
data.describe() # pandas.core.frame.DataFrame

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [49]:
# pandas가 numpy기반이라서 numpy의 기능을 사용할 수 있다.
# 행열의 전치도 가능하다.
data.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [52]:
data.describe(include=['object'])
data.describe(include=['O'])

smoker  day    time
count     244  244     244
unique      2    4       2
top        No  Sat  Dinner
freq      151   87     176

In [57]:
data.describe(include=[np.number]) # 숫자 all type
data.describe(include=np.float64)  # 숫자 type float64

total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

In [58]:
data.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [63]:
data['day'].values # 1차원 array로 return

# len()과 .size로 요소의 개수 return
print(len(data['day'].values))
print(data['day'].values.size)

244
244


In [66]:
# unique()는 column의 고윳값을 return(Series 한정)
print(data['day'].unique())

print('\n')

# value_counts()는 unique한 값과 개수를 return(Series 한정)
print(data['day'].value_counts())

['Sun' 'Sat' 'Thur' 'Fri']


Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64


주말고객수와 평일고객수를 구하기

In [ ]:
data[(data['sex']=='Female') & (data['day']=='Fri')]
data[data['sex']=='Female']['sex'].unique()

In [88]:
data[data['day']=='Sat']['day'].unique()
data[(data['day']=='Sat') + (data['day']=='Sun')]['day'].value_counts()
data[(data['day']=='Thur') + (data['day']=='Fri')]['day'].value_counts()

Thur    62
Fri     19
Name: day, dtype: int64

In [92]:
# 요일별 고객수 가져오기.
data['day'].value_counts()

# True와 False로 주말과 평일 고객수를 나눌 수 있다.
((data['day']=='Sat') | (data['day']=='sun')).value_counts()

False    157
True      87
Name: day, dtype: int64

In [95]:
# in 을 이용해서 고객수 나누기.
# .isin()을 이용하기.
data['day'].isin(['Sat','Sun']).value_counts()

True     163
False     81
Name: day, dtype: int64

where

In [96]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [97]:
# where의 인자는 조건이다.
# 조건만 있을 경우 True의 위치를 return

np.where(a>30)

(array([3, 4]),)

In [101]:
# where의 인자 개수에 따라서 기능이 달라진다.
# 조건이 True이면 a+1, False이면 a를 return

np.where(a>30, a+1, a)

array([10, 20, 30, 41, 51])

In [102]:
# 기본 통계 정보
# .discribe()

# pandas 에서 제공하는 함수
# .count : 개수
# .mean : 평균
# .std : 표준편차
# .min : 최솟값
# .max : 최댓값

data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [103]:
data['tip'].count()

244

descirbe() 결과를 numpy에서 제공하는 함수

In [104]:
import numpy.ma as ma

In [107]:
# data에서 'tip' column 가져오기.
kk = data.values[:, 1].copy()
kk

array([1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96, 3.23, 1.71,
       5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71, 3.5, 3.35, 4.08, 2.75,
       2.23, 7.58, 3.18, 2.34, 2.0, 2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45,
       3.27, 3.6, 2.0, 3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0,
       5.0, 6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0, 1.5,
       1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15, 2.47, 1.0, 2.01,
       2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25, 3.08, 4.0, 3.0, 2.71, 3.0,
       3.4, 1.83, 5.0, 2.03, 5.17, 2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0,
       4.3, 3.25, 4.73, 4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08,
       1.64, 4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5, 5.07,
       1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2, 1.48, 2.0, 2.0,
       2.18, 1.5, 2.83, 1.5, 2.0, 3.25, 1.25, 2.0, 2.0, 2.0, 2.75, 3.5,
       6.7, 5.0, 5.0, 2.3, 1.5, 1.36, 1.63, 1.73, 2.0, 2.5, 2.0, 2.74,
       2.0, 2.0, 5.14, 5.0, 3.75, 2.61, 2.0, 3.5, 2.5, 2.0, 2.0, 3.

In [114]:
xx = ma.array(data.values[:, 1])
xx

masked_array(data=[1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96,
                   3.23, 1.71, 5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71,
                   3.5, 3.35, 4.08, 2.75, 2.23, 7.58, 3.18, 2.34, 2.0,
                   2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45, 3.27, 3.6, 2.0,
                   3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0, 5.0,
                   6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0,
                   1.5, 1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15,
                   2.47, 1.0, 2.01, 2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25,
                   3.08, 4.0, 3.0, 2.71, 3.0, 3.4, 1.83, 5.0, 2.03, 5.17,
                   2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0, 4.3, 3.25, 4.73,
                   4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08, 1.64,
                   4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5,
                   5.07, 1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2,
                   1.48, 2.0, 2.0, 2.18, 1.5, 2.83, 1.5,

In [118]:
print(dir(xx))
# .count : 개수
# .mean : 평균
# .std : 표준편차
# .min : 최솟값
# .max : 최댓값

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', 

In [120]:
ma.count(xx)
xx.count()

244

https://wikidocs.net/159927