<a href="https://colab.research.google.com/github/minsaee/ai_chat_python/blob/master/601_%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC_%EB%B2%94%EC%A3%BC%ED%98%95%EB%B3%80%EC%88%98%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 변수
기계학습에서는  column = feature = dimension = variable을 혼용해서 사용한다.  


1 범주형 변수(Categorical Data)=질적변수(Qualitative Variable) : 몇개의 범주로 나누어진 자료를 의미
 - 명목형(Nominal Data): 성별, 성공여부, 혈액형 등 순서를 매길 수 없고 셀수 있다는 특징이 있다.
 - 순서형(Ordinal Data) : 교육수준, 만족도등  그들 사이에 순서 관계가 존재하는 자료


2 수치형 변수 = 양적변수(Quantitative Variable): 이산형과 연속형으로 이루어진 자료를 의미
  - 이산형(Discrete Data) :출산횟수, 불량품 수, 사고건수, 차량대수 등 이산적인 값을 갖는 데이터로  수치적인 의미를 가지나 소수점의 형태로 표현되지 못하는 데이터를 의미
  - 연속형(Continuous Data) : 신장, 체중, 시간, 길이 등 연속적인 값을 가지고 소수점으로 표현이 가능한 데이터를 의미




|        |  질적변수(Category)      | 양적변수(Numeric)          |
|--- |--- |---|
|질적변수|Cross Table               | Box Plot                   |
|        |Mosaic Plot               | 범주(Category)별 통계분석  |
|양적변수|Box Plot                  | Correlation                |
|        |범주(Category)별 통계분석 | Regression                 |
|        |                          | Scatter Plot               |


더미변수란 범주형 변수에 있는 범주 각각을 컬럼으로 변경하고, 원본 컬럼의 값이 해당 범주에 속하는지 여부에 따라 1 혹은 0으로 채운 변수이다.  




pd.get_dummies(df, columns=['범주형변수'])
- 범주형 변수 변환
  - 원핫인코딩(One-hot-encoding), 더미코딩(dummy coding),   이펙트코딩(Effect coding), 숫자로 표현된 범주형 특성,   레이블인코딩(Label encoding), 특징 해싱(Feature Hashing)  


- 수치형 변수 변환 (*옆의 괄호는 Scikit Learn의 함수명)
  - 선형변환: 최소최대 스케일링(MinMaxScaler), 표준화(StandardScaler), 로버스트 스케일링(RobustScaler), 균등분포/RankGauss (QuantileTransformer)
  - 비선형변환: 로그변환, 거듭제곱변환(PowerTransformer - Boxcox, YeoJohnson), 정규화(Normalizer - L1, L2, Max)
  - 기타: 구간분할 (=이산화, binning), 순위 변환



In [3]:
# iris데이터의 target값인 범주형 변수를 더미변수 형태로 대체하기.

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

load_iris = load_iris()
# print(load_iris)
print(dir(load_iris))
print(type(load_iris))
# print(load_iris.DESCR)


['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']
<class 'sklearn.utils._bunch.Bunch'>


In [32]:
iris = pd.DataFrame(load_iris.data, columns = load_iris.feature_names)
iris['target'] = load_iris.target
iris.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
29                 4.7               3.2                1.6               0.2   
128                6.4               2.8                5.6               2.1   
73                 6.1               2.8                4.7               1.2   
27                 5.2               3.5                1.5               0.2   
130                7.4               2.8                6.1               1.9   

     target  
29        0  
128       2  
73        1  
27        0  
130       2

In [33]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [34]:
iris['target'] = iris['target'].replace([0,1,2],['Setosa','Versicolour','Virginica'])
# iris['target'] = iris['target'].map({0:'Setosa', 1:'Versicolour', 2:'Virginica'})

In [35]:
iris['target']

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: target, Length: 150, dtype: object

In [36]:
iris.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
83                6.0               2.7                5.1               1.6   
37                4.9               3.6                1.4               0.1   
53                5.5               2.3                4.0               1.3   
70                5.9               3.2                4.8               1.8   
42                4.4               3.2                1.3               0.2   

         target  
83  Versicolour  
37       Setosa  
53  Versicolour  
70  Versicolour  
42       Setosa

In [37]:
# iris dataset의 target변수의 값을 더미로 처리하기.
iris_dummy = pd.get_dummies(iris, columns = ['target'])
iris_dummy.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
143                6.8               3.2                5.9               2.3   
9                  4.9               3.1                1.5               0.1   
72                 6.3               2.5                4.9               1.5   
79                 5.7               2.6                3.5               1.0   

     target_Setosa  target_Versicolour  target_Virginica  
145              0                   0                 1  
143              0                   0                 1  
9                1                   0                 0  
72               0                   1                 0  
79               0                   1                 0

### label encoding
 - label encoding은 문자열 데이터에 고유한라벨 번호를 매기는 것이다.

In [38]:
import seaborn as sns

In [39]:
iris = sns.load_dataset('iris')
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
41            4.5          2.3           1.3          0.3      setosa
89            5.5          2.5           4.0          1.3  versicolor
70            5.9          3.2           4.8          1.8  versicolor
32            5.2          4.1           1.5          0.1      setosa
117           7.7          3.8           6.7          2.2   virginica

In [40]:
# 실제 데이터 값이 바뀌지는 않는다.
iris.species.map({'versicolor':0, 'virginica':1, 'setosa':2})

0      2
1      2
2      2
3      2
4      2
      ..
145    1
146    1
147    1
148    1
149    1
Name: species, Length: 150, dtype: int64

In [41]:
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
38           4.4          3.0           1.3          0.2      setosa
75           6.6          3.0           4.4          1.4  versicolor
84           5.4          3.0           4.5          1.5  versicolor
50           7.0          3.2           4.7          1.4  versicolor
73           6.1          2.8           4.7          1.2  versicolor

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
ll = LabelEncoder()

In [45]:
# ll.fit_transform(iris.species)
ll.fit_transform(iris['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
# fancy indexing을 이용한 2차원으로 입력하면 경고창이 뜬다.
# A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel(). y = column_or_1d(y, warn=True)
# ll.fit_transform(iris[['species']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
from sklearn.utils import column_or_1d

column_or_1d(iris['species'])
ll.fit_transform(column_or_1d(iris['species']))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
41            4.5          2.3           1.3          0.3      setosa
48            5.3          3.7           1.5          0.2      setosa
130           7.4          2.8           6.1          1.9   virginica
56            6.3          3.3           4.7          1.6  versicolor
43            5.0          3.5           1.6          0.6      setosa

### one hot encoding
 - 문자열 데이터를 column으로 바꾸고, 해당하는 위치에만 1로한다.

In [53]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
ohe = OneHotEncoder()

sparse matrix
 - 성긴 행렬은 행렬의 값이 대부분 0인 경우를 가리키는 표현이다.
 - 그와 반대되는 표현으로는 밀집행렬, 조밀행렬이 사용된다.
 - 개념적으로 성김은 시스템들이 약하게 연결된 것에 해당한다.
 -  한 줄로 나열된 공과 공이 스프링으로 양 옆으로 하나씩 연결되었을 때 이것은 성긴 시스템이다.

In [57]:
# 2차원
ohe.fit_transform(iris[['species']])

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [58]:
ohe.fit_transform(iris[['species']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [60]:
# inverse_tranform으로 복구 가능하다.
ohe.inverse_transform([[1,0,0],[0,1,0],[0,0,1]])

array([['setosa'],
       ['versicolor'],
       ['virginica']], dtype=object)